"""AI-content detection scoring.

Primary: GPTZero (`/v2/predict/text`) returns a calibrated 0–1 probability.
Fallback: Claude scoring prompt that returns a single float.

Returns 0.5 (neutral) if both paths fail, so REVISOR can decide whether to
flag rather than hard-failing on a transient outage.
"""

import logging
import re
from typing import Optional

import httpx
from anthropic import AsyncAnthropic

from src.config.settings import settings

logger = logging.getLogger(__name__)

# Threshold above which content is flagged as likely AI-generated
DETECTION_THRESHOLD: float = 0.70

# GPTZero API endpoint
_GPTZERO_URL = "https://api.gptzero.me/v2/predict/text"

# Neutral score returned when both detection paths fail
_NEUTRAL_SCORE = 0.5

# Claude fallback prompt — must return a single float on the first line
_FALLBACK_PROMPT = """You are an AI-content detector. Read the text below and
return a single floating-point number between 0.0 and 1.0 indicating the
probability that the text was generated by an LLM rather than written by a
human. Return ONLY the number on the first line, no other text.

TEXT:
{text}
"""


class AIDetectionError(Exception):
    """Raised when both the primary and fallback detection paths fail."""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def score_text(text: str) -> float:
    """Score how AI-generated `text` appears, in the range 0.0–1.0.

    1.0 = definitely AI, 0.0 = definitely human, 0.5 = neutral / unknown.
    Tries GPTZero first; falls back to Claude if GPTZero is unconfigured
    or fails. Returns 0.5 if both fail.
    """
    if settings.gptzero_api_key:
        score = await _score_via_gptzero(text)
        if score is not None:
            return score
        logger.warning("GPTZero unavailable, falling back to Claude heuristic")
    else:
        logger.debug("GPTZero unconfigured, using Claude fallback")

    score = await _score_via_claude(text)
    if score is not None:
        return score

    logger.error("Both GPTZero and Claude fallback failed; returning neutral 0.5")
    return _NEUTRAL_SCORE


# ---------------------------------------------------------------------------
# Primary: GPTZero
# ---------------------------------------------------------------------------


async def _score_via_gptzero(text: str) -> Optional[float]:
    """Query GPTZero. Returns None on any error so the caller can fall back."""
    headers = {
        "x-api-key": settings.gptzero_api_key,
        "Content-Type": "application/json",
    }
    payload = {"document": text}

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            response = await client.post(_GPTZERO_URL, json=payload, headers=headers)
    except httpx.HTTPError as exc:
        logger.error("GPTZero network error", extra={"error": str(exc)})
        return None

    if not response.is_success:
        logger.error(
            "GPTZero non-2xx",
            extra={"status": response.status_code, "body": response.text[:200]},
        )
        return None

    try:
        body = response.json()
        prob = body["documents"][0]["completely_generated_prob"]
        return float(prob)
    except (KeyError, IndexError, TypeError, ValueError) as exc:
        logger.error("GPTZero malformed response", extra={"error": str(exc)})
        return None


# ---------------------------------------------------------------------------
# Fallback: Claude scoring prompt
# ---------------------------------------------------------------------------


async def _score_via_claude(text: str) -> Optional[float]:
    """Ask Claude to score the text. Returns None on any error."""
    try:
        client = AsyncAnthropic(api_key=settings.anthropic_api_key)
        response = await client.messages.create(
            model=settings.writer_model,
            max_tokens=10,
            messages=[
                {"role": "user", "content": _FALLBACK_PROMPT.format(text=text[:4000])},
            ],
        )
    except Exception as exc:
        logger.error("Claude fallback error", extra={"error": str(exc)})
        return None

    if not response.content:
        return None

    raw = response.content[0].text.strip().splitlines()[0].strip()
    match = re.search(r"\d*\.?\d+", raw)
    if not match:
        logger.error("Claude fallback returned non-numeric", extra={"raw": raw[:50]})
        return None

    try:
        score = float(match.group(0))
    except ValueError:
        return None

    return max(0.0, min(1.0, score))
